version: "3.9"

services:
  # ── Base de Datos Local ──
  simi-db:
    build:
      context: ./database
    container_name: simi-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: simidb
      POSTGRES_USER: simiuser
      POSTGRES_PASSWORD: simipass123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # ── Backend / Frontend Local ──
  simi-frontend:
    build:
      context: ./frontend
    container_name: simi-frontend
    ports:
      - "80:80"
    environment:
      PORT: 80
      DB_HOST: simi-db # Se conecta directamente al nombre del contenedor
      DB_PORT: 5432
      DB_NAME: simidb
      DB_USER: simiuser
      DB_PASSWORD: simipass123
      DB_SSL: "false"  # Desactivado localmente para que no rechace la conexión
      JWT_SECRET: secreto_local_123
    depends_on:
      - simi-db

volumes:
  pgdata:
    driver: local